spring.application.name=spring-boot_mvc

spring.datasource.driver=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://185.125.202.187:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=secret